Added SSL support to POP3/SMTP including certificate handling and config in obscrete.conf. Added a PIN to obscrete.conf

diff --git a/bin/mkconfig b/bin/mkconfig
--- a/bin/mkconfig
+++ b/bin/mkconfig
@@ -1,16 +1,22 @@
 #!/bin/sh
 
+erl=`which erl`
+if [ -z "${erl}" ]; then
+    >&2 echo "Could not find erl in path!"
+    exit 1
+fi
+
 usage()
 {
-    >&2 echo "mkconfig square | circle | epfl | roma | it"
+    >&2 echo "mkconfig <CERTIFICATE-FILE> square | circle | epfl | roma | it"
     exit 100
 }
 
-if [ $# -lt 1 ]; then
+if [ $# -ne 2 ]; then
    usage
 fi
 
-case $1 in
+case $2 in
     square | circle | epfl | roma | it)
         ;;
     *)
@@ -18,14 +24,9 @@ case $1 in
         ;;
 esac
 
-erl=`which erl`
-if [ -z "${erl}" ]; then
-    >&2 echo "Could not find erl in path!"
-    exit 1
-fi
 
 bin_dir=${0%/*}
 erl_libs=${bin_dir}/../..
 pa="-pa ${erl_libs}/*/ebin"
 
-env ERL_LIBS=${erl_libs} ${erl} ${pa} -noshell -run simulator_mkconfig start $1
+env ERL_LIBS=${erl_libs} ${erl} ${pa} -noshell -run simulator_mkconfig start $1 $2
